services:
  mongodb:
    image: mongo:latest
    container_name: mongodb-scraper
    ports:
      - "27017:27017"
    networks:
      - gamesprer_network
    environment:
      MONGO_INITDB_ROOT_USERNAME: yinnohs
      MONGO_INITDB_ROOT_PASSWORD: 1234
      MONGO_INITDB_DATABASE: gamesprer
  
  scraper:
    image: gamesprer-scraper:latest
    container_name: gamesprer-scraper
    networks:
      - bridge_network
      - gamesprer_network
    depends_on: 
    - "mongodb"
    environment:
      MONGO_DB_URL: mongodb://yinnohs:1234@mongodb-scraper:27017/gamesprer?authSource=admin
  
  api:
    image: gamesprer-back:latest
    container_name: gamesprer-back
    ports:
      - "5052:5052"
    networks:
      - gamesprer_network
    depends_on: 
      - "mongodb"
    environment:
      spring.data.mongodb.uri: mongodb://yinnohs:1234@mongodb-scraper:27017/gamesprer?authSource=admin
      api.url: http://scraper:3000

networks:
  gamesprer_network:
    driver: macvlan
    ipam:
      config:
        - subnet: 192.168.1.0/24
          gateway: 192.168.1.1
  
  bridge_network:
    driver: bridge
